// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmfmztmbrkihjygkfqmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptZm16dG1icmtpaGp5Z2tmcW1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDc1MDUsImV4cCI6MjA2NDg4MzUwNX0.-ytmuV8Q1qwF5bVrIsQlf_jbC1dbjsOU-L3vCUQGKmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);